### ISSUE TITLE
Using the plugin with typescript seems not working

### ISSUE THREAD

**Issue by lionelB** [lodash/lodash-webpack-plugin#10]
Hello

I'm workign on a typescript project using lodash. We would love to use the webpack-plugin to decrease vendor bundle size but I can't figure how to make it work.
here is a version of my webpack config file
```javascript
  var webpackOptions = {
    entry: {
      app: './src/app/index.module.ts',
      vendor: ["lodash"],
    },
    resolve: { extensions: ['', '.ts'] }, 
    module: {
      preLoaders: [{ test: /\.ts$/, exclude: /node_modules/, loader: 'tslint-loader'}],
      loaders: [{
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: 'ng-annotate',
      }, {
        test: /\.ts$/,
        exclude: /node_modules/,
        loader:  'ts-loader',
        query: {
          'plugins': ['lodash']
        }
      }]
    },
    plugins: [
      new webpack.webpack.DefinePlugin({
        '__DEV__': JSON.stringify(process.env.NODE_ENV !== 'production'),
        'process.env': {
          'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
        }
      }),
      new LodashModuleReplacementPlugin,
      new webpack.webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
    ],
    output: { filename: 'index.module.js' }
  };
```
in typescript we import the module using the following syntax
```typescript
import {forEach, assign} from 'lodash';
```

the emitted `vendor.bundle.js`seems to contains the complete lodash lib... 
I guess I'm doing something wrong, but I can't figure what 
thanks for you help.

**Comment by jdalton** [comment]
Hi @lionelB!

For that syntax to auto-cherry-pick you'll need to use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) or manually cherry-pick
```js
import { assign } from 'lodash/assign';
```

See the post [Angular 2 with Babel](http://shuheikagawa.com/blog/2016/05/08/angular-2-with-babel/) for presets and plugins that cover the TypeScript gap.

**Comment by lionelB** [comment]
thx for your answer

**Comment by janmonschke** [comment]
@lionelB did you manage to get it working? It does not work for me, even when I set up babel and the babel plugin in combination with `ts-loader`.
