### ISSUE TITLE
Full Lodash library is included when using Lodash with webpack.ProvidePlugin

### ISSUE THREAD

**Issue by creage** [lodash/lodash-webpack-plugin#100]
I always had my lodash imports explicitly, like

```
import _ from 'lodash';
```
and it worked fine.

Recently I've tried to move this into [webpack.ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/)

```
new webpack.ProvidePlugin({
	$: 'jquery',
	jQuery: 'jquery',
	_: 'lodash'
})
```

and instead of ~60KBs of lodash bundle, now I have it ~500, meaning the cherry-picking is not applied.

Would be very nice it this could be fixed.

**Comment by jdalton** [comment]
Hi @creage!

From our readme:
> This plugin complements [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) by shrinking its cherry-picked builds even further!


You should check out  [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash).

**Comment by creage** [comment]
Well, actually, I'm using them both, and it is still broken.

I've created simple [repo ](https://github.com/creage/lodash-broken). If you run a
```
npm start
```

you'll see an output of two webpack entry points, where one is fine, and only needed parts are imported, while second is broken, having full lodash library imported.

I hope it helps.

**Comment by jdalton** [comment]
It looks like your missing a Lodash import [here](https://github.com/creage/lodash-broken/blob/master/lib.broken.js).

**Comment by creage** [comment]
No, I did intentionally, to utilise the webpack.ProvidePlugin. It allows to not to import lodash in every file, but define it once in webpack.config, and it will inject it automatically. And it works, but it injects full lodash library.

What I want to achieve, is same way of injecting, but only required parts of it, and not full library.

Is it possible?

**Comment by jdalton** [comment]
Ya that looks like a plugin ordering issue maybe. It might work if it injects the lodash require before the babel plugin is ran.

**Comment by creage** [comment]
AFAIK babel-loader compiles sources first, and then pipes them to webpack, which, in turn, injects Lodash, as in my case. I had a hope that lodash-webpack-plugin might process such injects as well.

Can't we make babel-plugin-lodash to inject
```
import _ from 'lodash';
```
automagically whenever it founds a reference to non-yet-imported Lodash? Then we'll have just to focus on coding, using all of Lodash power, without explicit imports.

**Comment by justsml** [comment]
Hey @creage One idea: Could you use the webpack banner plugin, with the `{raw: true}` option?

**Comment by creage** [comment]
@justsml well, it might do the trick, but I'd end with including it in every file, or what? If I go with checking/parsing the code to see if the Lodash is actually used within the module, then I'd be kinda reimplementing the plugin I'd like to have fixed, right?

**Comment by rdunk** [comment]
@creage Did you ever find a solution for this?

**Comment by creage** [comment]
@rdunk well, no. I ended up importing lodash explicitly where I use it.

**Comment by OlenDavis** [comment]
You can obviate the need for `babel-plugin-lodash` by getting creative with `ProvidePlugin` as follows and adopting a standard of using lodash utils like `_map(...)` everywhere in your code:

> **Note:** The `config` object in this example code is an instance of [`webpack-chain`](https://www.npmjs.com/package/webpack-chain)

```js
	const _ = require('lodash')

	config.plugin('provide').use(ProvidePlugin, [
		{
			_: 'lodash',
			..._.fromPairs(
				_.map(
					_,
					(fn, key) => typeof fn === 'function' && [`_${key}`, `lodash/${key}`],
				).filter(Boolean),
			),
		},
	])
```

So instead of assuming you can use `_` everywhere in your code, you can assume you can use `_map`, `_forEach`, `_zipObject` and so on everywhere in your code. 

> **Note:** Probably not a fit if you've gotten accustomed to using `_varName` to refer to private variables or the like. But even so, you could just change this to `__${key}` or whatever better jives with your variable naming style.
