### ISSUE TITLE
Could this plugin also convert per-method packages?

### ISSUE THREAD

**Issue by wmertens** [lodash/lodash-webpack-plugin#101]
I have a couple of deps that import e.g. `lodash.flatten`. I use `resolve.alias` to map those to e.g. `lodash/flatten`, and that works great (provided you use lodash and not lodash-es. I also map lodash-es to lodash).

However, it is tedious to find and write all the names. Can this plugin put an automatic resolver in place for `lodash.*`? I don't seem to find a way to do it from webpack configuration.

PS: the issue when aliasing `lodash` to  `lodash-es` is that the methods then become ES6 exports and that breaks ES5 code. I tried using exports-loader to no avail, and after measuring with webpack bundle analyzer it turns out that the minified code of lodash vs lodash-es is actually smaller despite being larger unminified, so now I alias `lodash-es` to `lodash`.

**Comment by TheLarkInn** [comment]
You could technically add resolver plugins to hi-jack requests. 👌

**Comment by jdalton** [comment]
Per method packages get tricky as they may not have all the other noop/short-out modules to rewire too. If you create an all-in-one lodash module aliaser/consolidator though that would be rad.

**Comment by wmertens** [comment]
So @jdalton, are you saying that simply pointing lodash.x to lodash/x won't
work?

**Comment by jdalton** [comment]
That would require folks having both packages which is an unknown. I'm also not continuing the individual packages beyond v4 so not wanting to put anymore time into them feature wise.

**Comment by TuckerWhitehouse** [comment]
It's probably not the best solution, but I've added the following snippet to my webpack config to dynamically generate the list of alises ¯\\_(ツ)_/¯

```js
const { _, toLower, transform } = require('lodash')

const lodashAlises = transform(_, (acc, val, key) => {
  acc[`lodash.${toLower(key)}`] = `lodash/${key}`
})

module.exports = { resolve: { alias: { ...lodashAlises } } }
```

**Comment by wmertens** [comment]
@TuckerWhitehouse great idea, thanks! I turned that into

```js
let lodashAliases
try {
	// See https://github.com/lodash/lodash-webpack-plugin/issues/101
	const lodash = require(require.resolve('lodash', {
		paths: [process.cwd()],
	}))

	lodashAliases = {
		// Optimize lodash-es, everybody should use lodash
		'lodash-es': 'lodash',
		'lodash-es/isEqualWith': 'lodash/isEqualWith',
		'lodash-es/isObject': 'lodash/isObject',
		'lodash-es/mapValues': 'lodash/mapValues',
		'lodash-es/merge': 'lodash/merge',
		'lodash-es/noop': 'lodash/noop',
		'lodash-es/toPath': 'lodash/toPath',
	}
	for (const key of Object.keys(lodash)) {
		if (typeof lodash[key] === 'function')
			lodashAliases[`lodash.${lodash.toLower(key)}`] = `lodash/${key}`
	}
} catch (error) {
	if (error.code !== 'MODULE_NOT_FOUND') throw error
}
```

and further down I spread that into the aliases. The require.resolve is to make sure it can find lodash even when installed as a module.
