### ISSUE TITLE
Enabling this plugin appears to be breaking lodash.omit

### ISSUE THREAD

**Issue by axelson** [lodash/lodash-webpack-plugin#102]
With this plugin enabled:

```
import omit from 'lodash/omit'
omit({'a-b':1}, 'a-b')
{'a-b': 1}
```

Without this plugin enabled:
```
import omit from 'lodash/omit'
omit({'a-b':1}, 'a-b')
{}
```

I tried disabling all the features but it still didn't fix the issue. It's possible I have some flaw in my setup, I'm not sure. I haven't noticed any other oddities with lodash.

Note: `omit` is only broken for keys with hyphens (maybe other characters, haven't tested).

Current versions:
* lodash: 4.17.4
* lodash-webpack-plugin: 0.10.7
* babel-plugin-lodash: 3.2.11

Any ideas?

**Comment by jdalton** [comment]
Hi @axelson!

Without enabling `flattening` you'll have to provide an array of properties to `omit`.
```js
omit({'a-b':1}, ['a-b'])
```

**Comment by axelson** [comment]
@jdalton I get the same behavior when passing in an array:

```
omit({'a-b':1}, ['a-b'])
Object {a-b: 1}
```

**Comment by jdalton** [comment]
I should fix that then. Try enabling `paths` and if that doesn't work then try also enabling `cloning`.

**Comment by axelson** [comment]
Okay, with enabling `flattening` makes `omit({'a-b':1}, ['a-b'])` work. And enabling both `paths` and `flattening` makes `omit({'a-b':1}, 'a-b')` work.

Just for reference here's the config I'm using to work-around this issue:
```
    new LodashModuleReplacementPlugin({
      flattening: true,
      paths: true
    }),
```
