### ISSUE TITLE
Enabling plugin appears to break lodash.map iteration over array

### ISSUE THREAD

**Issue by paolavness** [lodash/lodash-webpack-plugin#105]
I've enabled collections in webpack as follows:
```
        new LodashModuleReplacementPlugin({
            collections: true
            })
```
The below tho fails with an error, only when the plugin is enabled:
```
        const test = [ 
            {key: 'a', value: 1}, 
            {key: 'b', value: 2} ]
        _.map(test2)
```
Error is:
```
TypeError: iteratee is not a function
    at arrayMap (webpack:///./~/lodash/_arrayMap.js?:16:21)
    at map (webpack:///./~/lodash/map.js?:50:10)

```
 Error points to this block of code:
```
function arrayMap(array, iteratee) {
  var index = -1,
      length = array == null ? 0 : array.length,
      result = Array(length);

  while (++index < length) {
    result[index] = iteratee(array[index], index, array);   <----- Error here
  }
  return result;
}
```

Is there something additional I need to add to config in Webpack? I've adding in _exotics_ and _guards_ but the error remains.

**Comment by jdalton** [comment]
If you don't want to provide an iteratee then you'll have to add back things like `"shorthands"` which is super heavy. I'd suggest simply providing an identity function.

**Comment by paolavness** [comment]
@jdalton, could you say how an identity function would look to provide the same outcome as _.map(test2) in the above example? I've tried a couple of scenarios but am not getting the same result as when this plugin is not enabled.

Thanks again.

**Comment by jdalton** [comment]
_.map(test2, _.identity)
