### ISSUE TITLE
Apply on chunks

### ISSUE THREAD

**Issue by DevSide** [lodash/lodash-webpack-plugin#107]
I have some trouble to get the plugin working on common chunks.

The `embed` bundle is well optimized, but on the other hand, the `vendors` chunk bundle is not.
Changing the order between `LodashModuleReplacement` and  `CommonsChunk` has no effect.
Any ideas ?

```js
{
  entry: {
    client: '../src/client.js',
    embed: '../src/app/embed.js',
    ...
  }
  ...
  plugins: [
     new LodashModuleReplacementPlugin(),
     new webpack.optimize.CommonsChunkPlugin({
        name: 'vendors',
        chunks: ['client'],
        minChunks(module, count) {
          return count >= 2 || (module.context && module.context.indexOf('node_modules') !== -1);
        },
     }),
     ...
  ]
}
```
The module Lodash is even bigger in `vendors.bundle` actually.

![screenshot from 2017-04-28 12-01-18](https://cloud.githubusercontent.com/assets/6873926/25524481/049b5ce8-2c0b-11e7-8102-c627d47aaabe.png)![screenshot from 2017-04-28 12-03-54](https://cloud.githubusercontent.com/assets/6873926/25524488/0a2d2cae-2c0b-11e7-8010-5b23169f0e9b.png)

**Comment by jdalton** [comment]
Hi @DevSide!

Are you cherry-picking your Lodash method use, e.g. `require('lodash/union')` instead of `_.union`?
If not you should be doing that. If you're using Babel you can do this automagically with [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).

**Comment by smashercosmo** [comment]
The issue is still relevant. Plugin is not applied to extracted vendor chunk. Here is the example repo https://github.com/smashercosmo/lodash-webpack-plugin-issue

**Comment by smashercosmo** [comment]
Though it works without the explicit vendor chunk, if you extract vendor libs with
```js
new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: module => /node_modules/.test(module.resource)
})
```

**Comment by valmassoi** [comment]
+1 did you find a solution @smashercosmo ? I get the smaller lodash module from `LodashModuleReplacementPlugin` in my `app.min.js` AND the full lodash bundle in my `vendor.min.js`. I can remove it from my vendor list but would rather have it there
