### ISSUE TITLE
Each lodash

### ISSUE THREAD

**Issue by tselishev-semen** [lodash/lodash-webpack-plugin#110]
Hello, I have some interesting problem with your plugin, when i use it:
``` 
 new LodashModuleReplacementPlugin()
```
and then i use lodash.each
```
import {each} from 'lodash';
 each({a:1, b: 2}, (value, key) => {
        console.log('doesn\'t work')
    });
```
Each doesn't work correct, could you help me with this problem?

**Comment by tselishev-semen** [comment]
Each now looks like that
```
/**
 * A specialized version of `_.forEach` for arrays without support for
 * iteratee shorthands.
 *
 * @private
 * @param {Array} [array] The array to iterate over.
 * @param {Function} iteratee The function invoked per iteration.
 * @returns {Array} Returns `array`.
 */
function arrayEach(array, iteratee) {
  var index = -1,
      length = array == null ? 0 : array.length;

  while (++index < length) {
    if (iteratee(array[index], index, array) === false) {
      break;
    }
  }
  return array;
}

module.exports = arrayEach;
```
and this is strange

**Comment by restrry** [comment]
check https://github.com/lodash/lodash-webpack-plugin#feature-sets
by default objects in collections aren't supported. if you need it, configure:
```
new LodashModuleReplacementPlugin({
  'collections': true
});
```

**Comment by tselishev-semen** [comment]
Thanks, it works. But in my opinion, these options must be true by default

**Comment by jdalton** [comment]
@tselishev-semen 
> But in my opinion, these options must be true by default

That defeats the entire purpose of this opt-in plugin which is to create smaller Lodash builds by replacing feature sets of modules with `noop`, `identity`, or simpler alternatives. With this plugin you start with minimal features/functionality and opt-in to the feature sets you want.
