### ISSUE TITLE
Identify which lodash method would require which plugin option

### ISSUE THREAD

**Issue by karanjthakkar** [lodash/lodash-webpack-plugin#112]
I'm using this with my webpack configuration and have found that at times my code doesn't work as expected. This is obviously because I did not enable one of the options that this plugin exposes. Would it possible to find a list which would essentially be something like:

1. sortBy, uniqBy, etc.  requires `flattening `
2. map, etc. requires `collections`

Thanks!

**Comment by jdalton** [comment]
If there's a method that's fundamentally broken without a feature we should be enabling it by default when the method is used. So if `sortBy` just doesn't work without `flattening` then we should fix that. However, `map` is fine without `collections` and the `collections` feature is self explaining enough for most folks to get it.

**Comment by karanjthakkar** [comment]
@jdalton Maybe I wasn't clear in explaining. My bad. This library is super useful and the defaults are perfect. What I wanted to know was if you could point me to the code which would would help me understand caveats [like these](https://github.com/lodash/lodash-webpack-plugin/issues/99#issuecomment-285398594) so I make sure no one in my team gets into these pitfalls.

**Comment by raine** [comment]
`uniqBy` produces wrong result without `flattening: true`, so I'm wondering if its usage should override configuration?
