### ISSUE TITLE
Using _.find

### ISSUE THREAD

**Issue by JeffreyArts** [lodash/lodash-webpack-plugin#113]
Hi,

What happens with the lodash **find** function with this package? Since it throws the following error when I try to use it `predicate is not a function`. 

When I change the webpack configuration by adding `"shorthands": true`, it does not throw the error anymore. But doesn't seem to work as it should neither, since the result is `undefined`.

When I log the values before the `_.find` function call in my script, and use those values in the console on the same page it threw me the error before. It works as it should, and gives the expected result.

Would like to know what the **shorthands** parameter actually stands for as well, that isn't really clear to me :-)

**Comment by jdalton** [comment]
You'll need to enable the `"shorthands"` feature set if you want to pass anything other than a function predicate. I don't recommend that however because `"shorthands"` is an expensive (as in file size) feature set.

**Comment by sqpdln** [comment]
I got this problem as well.

`_.find(a, ['c', 5])` returns `undefined`, without throwing any error, and with `shorthands: true` in the config.
