### ISSUE TITLE
Browserify alternative

### ISSUE THREAD

**Issue by sassanh** [lodash/lodash-webpack-plugin#115]
Is there a browserify alternative for this plugin?

**Comment by jdalton** [comment]
Hi @sassanh!

There hasn't been demand. All signs point to it as something that we used to know.

<img src=https://user-images.githubusercontent.com/4303/28442715-a449099c-6d66-11e7-9bb7-bd8bcf8cedb2.png width=80%>

**Comment by sassanh** [comment]
https://www.npmjs.com/package/browserify 90,000 downloads per day doesn't seem to be a sign that points to it as "something we used to know".

Even if browserify is something we used to know, if webpack is the thing "we currently know" I rather stay single with the memories of browserify as I can't communicate with someone who reminds me of gulp. Browserify is honest in every details of compilation process with me, webpack and alike wear so much makeup but are hard to deal with as they hide many details.

**Comment by jdalton** [comment]
@sassanh webpack had 350,000 and Lodash has almost 2 million in the last day. I'm not super interested in why you personally are tied to dead or nearly dead projects.

**Comment by sassanh** [comment]
Good to know you chose a democratic way to get to a conclusion about supporting Browserify, bad news is democracy leads to things like Donald J Trump when people are not interested to hear "why"s and just follow the media and social networks. Maybe if Browserify was a repository owed by someone who had relations in Facebook, it could get boosted as much as webpack.

The obvious thing for me is Browserify is the right way to bundle and Webpack is the wrong way to bundle. So I'm gonna keep using Browserify even if lodash adds a few KBs of code when bundled with Browserify.
