### ISSUE TITLE
There's something wrong

### ISSUE THREAD

**Issue by zhuanqizhirou** [lodash/lodash-webpack-plugin#118]
My webpack config looks like below.The problem is : _.get({"a":{"b":["c","d”]}},"a.b",[]),it returns [].
After i remove the config, it works right.

===================
1.
//var LodashModuleReplacementPlugin = require('lodash-webpack-plugin');
2.
rules: [
                {
                    test: /\.(jsx|js)?$/,
                    exclude: /node_modules/,
                    use: [
                        {
                            loader: 'babel-loader',
                            options: {
                                //plugins: ['lodash'],
3.
        plugins: [
            //new LodashModuleReplacementPlugin,

**Comment by jdalton** [comment]
Hi @zhuanqizhirou!

You'll need to enable the "paths" [feature set](https://github.com/lodash/lodash-webpack-plugin#feature-sets).

**Comment by zhuanqizhirou** [comment]
Thank you very much!
