### ISSUE TITLE
Replace with functions which throw error instead of "simpler" alternatives

### ISSUE THREAD

**Issue by itsuryev** [lodash/lodash-webpack-plugin#123]
I struggle to understand how to use this plugin correctly. I have existing codebase and would like to reduce its' size. It is not clear what feature sets should be enabled or not.

We've encountered issue where we were mutating state. How did that happen? 
Turns out we were using _.clone (single usage in the whole app in pretty abandoned place) which is replaced with _.identity after plugin. But this could only lead to errors, why not to replace it with function which throws an error "Hey, you are using clone, most likely you need to enable 'cloning' feature set".

In case of some sets it's not clear how they relate to used functions, e.g. guards.

If all replaced functions threw error I would have more confidence in this change - at least I could click through the whole app, check console that there are no errors and commit. Right now something might be failing somehow and it is not apparent.

**Comment by jdalton** [comment]
Hi @itsuryev!

You can start by enabling all feature sets and then working your way backwards. If you're still running into issue then maybe the plugin isn't right for your project. You can always use it when starting a fresh project.
