### ISSUE TITLE
What are the benifits of using this plugin over using the babel-plugin-lodash

### ISSUE THREAD

**Issue by Ilyes512** [lodash/lodash-webpack-plugin#124]
Hey,

I was wondering what the benefits are from using this plugin instead of using the babel-plugin directly.

FYI I am using webpack2 with the babel-loader (vue-cli project generated using the webpack template).

**Comment by jdalton** [comment]
Hi @Ilyes512!

This plugin in a companion to `babel-plugin-lodash` that disables many feature sets by default, letting you opt-in to features to improve bundle size.

**Comment by JSteunou** [comment]
@jdalton I'm sorry I still dont get why this might be needed for. I though the babel plugin will transform *import* to make our build the right size by importing just the truly used lodash function. If this is the case, how can we remove more stuff without breaking our build?

**Comment by jdalton** [comment]
Hi @JSteunou 
> If this is the case, how can we remove more stuff without breaking our build?

This plugin removes feature sets through remapping of certain modules to noop implementations.
When adopting for an existing project you'll want to enable all features and then turn off features as needed.

**Comment by JSteunou** [comment]
Does that mean `babel-plugin-lodash` is not efficient enough and let some part of lodash import entire feature sets?
