### ISSUE TITLE
Rollup support broken?

### ISSUE THREAD

**Issue by sebastianbarfurth** [lodash/lodash-webpack-plugin#126]
I know it's not meant for Rollup, but trying to use it with Rollup seems to error out:

    TypeError: Cannot read property 'resolveId' of undefined

It's obviously not receiving nodeResolve. I tried manually passing it ``rollup-plugin-node-resolve``, but that made ``resolveId`` return null, which then fails on ``.then``.

Any idea what could be causing this? Or are the days of unofficial Rollup support for this just over?

**Comment by jdalton** [comment]
I should document this better. Maybe you'd like to contribute once we iron out your use case. Rollup plugins don't build off each other well so you have to wrap them. To do this you'll want to do.
```js
const nodeResolve = require("rollup-plugin-node-resolve")
// then later when specifying plugins
lodashWebpackPlugin(nodeResolve(), options)
```

**Comment by sebastianbarfurth** [comment]
Interestingly enough that gives me this:

    TypeError: Cannot read property 'then' of null

I can push my whole repo (or rather my work) if you wanna see it for debugging, if you care about Rollup support at all that is.

**Comment by jdalton** [comment]
A repro repo would be great!

**Comment by sebastianbarfurth** [comment]
You can check [here](https://github.com/sebastianbarfurth/vee-validate/tree/improvement/use-lodash) for the repo this is happening on. Just clone and ``npm install``.

You then want to run:

```
npm run build:bundle
```

You'll get the error as I described (I hope). The build file is located in `build/main.js`.

**Comment by jdalton** [comment]
I notice you have multiple `nodeResolve()` invocations. I think the idea is to use 1 and have it be the wrapped form, `lodashWebpackPlugin(nodeResolve(), options)`.

**Comment by jdalton** [comment]
Ok, I'll try to dig in more this evening and see what's up.
*(my hunch is something in rollup may have changed)*

**Comment by sebastianbarfurth** [comment]
That'd be cool!

**Comment by realityking** [comment]
I just hit `TypeError: Cannot read property 'then' of null` as well. Did you you discover anything @jdalton?

**Comment by jdalton** [comment]
Ah nope, didn't.
