### ISSUE TITLE
More docs or scan tool

### ISSUE THREAD

**Issue by casey-speer** [lodash/lodash-webpack-plugin#127]
I agree with https://github.com/lodash/lodash-webpack-plugin/issues/112.

Maybe I'm just misunderstanding, but I'm unclear from the README whether there are any features I must opt into if I am using the feature in my code. For example, if I call to `memoize` in my code, must I opt in to `memoize` in the plugin? Or will the plugin detect the usage and opt-in without configuration? If I must opt in, could there be more docs to map individual functions to feature sets?

If it is required to manually opt-in to features used in code, then perhaps an alternative to more docs would be a static analysis tool that tries to find simple usages of the lodash tools, maps them to the feature sets required, and reports which features to enable.

**Comment by jdalton** [comment]
This plugin isn't sophisticated and I like it like that. If peeling functionality away is a pain, wait and use it on a new project and start with everything off, opting-in as needed. Lodash v5 will be simpler to start with so I don't want to invest more time in making Lodash v4 palatable.
