### ISSUE TITLE
sortBy => iteratee is not a function

### ISSUE THREAD

**Issue by valorize** [lodash/lodash-webpack-plugin#128]
Hi,
I ran into the issue that when usingsortBy like `sortBy(points, 'lng')`
that `iteratee is not a function`. In my case it was obfuscated through UglifyJsPlugin which resultet in `t is not a function`. It took me some hours to identify lodash to be the source.

I read in the thread https://github.com/lodash/lodash-webpack-plugin/issues/105 that I have to use a identity function.

My question now: Could we throw a more helpfull message like: please define a iteratee function in sortBy?

**Comment by jdalton** [comment]
Hi @valorize!

You'll need to enable the *"shorthands"* [feature set](https://github.com/lodash/lodash-webpack-plugin#feature-sets), but I would try to avoid it since that is one of the heavier features. Instead you can do `(o) => o.lng` or `_.property('lng')`.

**Comment by valorize** [comment]
Hmm even with the identity function I get `t is not a function`. The non uglified version of sortBy is:
```
function() {
    var args = arguments,
        index = -1,
        length = nativeMax(args.length - start, 0),
        array = Array(length);

    while (++index < length) {
      array[index] = args[start + index];
    }
    index = -1;
    var otherArgs = Array(start + 1);
    while (++index < start) {
      otherArgs[index] = args[index];
    }
    otherArgs[start] = transform(array);
    return apply(func, this, otherArgs);
  }
```

**Comment by jdalton** [comment]
Try passing an array:
```
_.sortBy(points, [func])
```

**Comment by valorize** [comment]
Thanks that was the missed info.
