### ISSUE TITLE
after build fill function do not work 

### ISSUE THREAD

**Issue by shirleyMHao** [lodash/lodash-webpack-plugin#129]
I user lodash-webpack-plugin combine with babel-plugin-lodash 
after build the _fill function seems not work properly. 
Code as bellow: 
`import _ from 'lodash'
 let arr = new Array(3);
 _.fill(arr, false);
console.log(arr);
`
console print [null, null, null]

**Comment by jdalton** [comment]
It's not obvious what the issue could be. Looking at the source of `fill` I don't see anything affecting the value assignment. Could you try enabling feature sets in `lodash-webpack-plugin` one by one until it starts working?

**Comment by sincraianul** [comment]
This issue is still occurring. I don't understand why it's closed.

**Comment by falsyvalues** [comment]
@sincraianul If so try to post something that will help us to track problem, reproducible example would be nice.

**Comment by sincraianul** [comment]
Enabling `coercions` did the trick.

**Comment by sincraianul** [comment]
Opened PR #135.

**Comment by falsyvalues** [comment]
@sincraianul Thanks!
