### ISSUE TITLE
The function 'has'  use does not normally after package

### ISSUE THREAD

**Issue by wulunyi** [lodash/lodash-webpack-plugin#131]
```
import { has } from 'lodash';

let test = {
    status: {code: 0}
}

console.log(has(test, 'status.code'));
// before package true
// after package false
```
// Package result
![image](https://user-images.githubusercontent.com/15170275/33594561-5d7f3164-d9cf-11e7-8718-3df8e33b4a02.png)

// This is I want
![image](https://user-images.githubusercontent.com/15170275/33594853-95805240-d9d0-11e7-83d3-736be63ea287.png)

**Comment by jdalton** [comment]
Hi @wulunyi!

You'll need to enable the "paths" feature set.

**Comment by wulunyi** [comment]
Thanks
