### ISSUE TITLE
`_.each` is compiled to `arrayEach`

### ISSUE THREAD

**Issue by imcuttle** [lodash/lodash-webpack-plugin#133]
when I use lodash-webpack-plugin, unfortunately, the method `_.each` will translate to `arrayEach`

```javascript
import _ from 'lodash'

const obj = {
  a: 'a',
  b: 'b'
}

_.each(obj, (v) => {
  // log nothing
  console.log(v)
})
```

**Comment by jdalton** [comment]
Hi @imcuttle!

This is by design. If you want collections then you need to enable the "collections" feature set.

**Comment by lili21** [comment]
You can't decide which method the developer can or cannot use. especially for third-part code. I don't know if they use the `collections` feature or not. so I have to enable all the feature sets.
