### ISSUE TITLE
cann`t work with antd

### ISSUE THREAD

**Issue by chowsource** [lodash/lodash-webpack-plugin#134]
if build with lodash-webpack-plugin,click submit button, runtime error
![image](https://user-images.githubusercontent.com/5119971/35510493-3bad75d4-0533-11e8-9368-d63fbe6ffef5.png)

![image](https://user-images.githubusercontent.com/5119971/35510596-abd38826-0533-11e8-8637-2a3a0026328c.png)

if build not with lodash-webpack-plugin,it`s OK
![image](https://user-images.githubusercontent.com/5119971/35510526-5f17c786-0533-11e8-8a99-88f0914cc373.png)

bug demo git:https://github.com/chowsource/antd-datepicker-bug-demo.git

**Comment by jdalton** [comment]
Hi @chowsource!

Start will all the feature sets enabled, then turn them off one by one until your build breaks.

**Comment by chowsource** [comment]
@jdalton thank you, resolve it.
```javascript
new LodashModuleReplacementPlugin({
          paths: true,
      }),
```
needs to set 'paths' as true
