### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by MaelWeb** [lodash/lodash-webpack-plugin#148]
I have get the warning "DeprecationWarning: Tapable.plugin is deprecated." for webpack 4.

**Comment by MaelWeb** [comment]
repeate issues

**Comment by falsyvalues** [comment]
Hi @MaelWeb

This [has been patched](https://github.com/lodash/lodash-webpack-plugin/commit/198e1f0ee9700f8067c21c036a23dd8cfdfe05ee) and just needs a release.

Dup of #142.
