### ISSUE TITLE
use _.orderBy  is worng

### ISSUE THREAD

**Issue by xiemms** [lodash/lodash-webpack-plugin#150]
https://github.com/lodash/lodash-webpack-plugin/blob/25c423cf3eed73dea06099e93401d9d01f8fc1cd/src/mapping.js#L123

**Comment by xiemms** [comment]
![image](https://user-images.githubusercontent.com/16432738/39224356-8ed463ec-4879-11e8-99fe-cf52329d8aae.png)
![image](https://user-images.githubusercontent.com/16432738/39224359-934ae108-4879-11e8-9d91-0a6695768d49.png)

**Comment by xiemms** [comment]
![image](https://user-images.githubusercontent.com/16432738/39224443-ff0979d6-4879-11e8-8492-09fc978581fd.png)

**Comment by xiemms** [comment]
i change    'shorthands': [['_baseIteratee', 'identity']]   to   'shorthands': [['_baseIteratee', '_baseIteratee']]  
it's ok

**Comment by jdalton** [comment]
Hi @xiemms!

If you'd like to enable shorthands you can do so with the plugin options.

**Comment by xiemms** [comment]
ok. thx
