### ISSUE TITLE
lodash-webpack-plugin (v.0.11.5) breaks react-google-maps (v9.4.5)

### ISSUE THREAD

**Issue by aziolek** [lodash/lodash-webpack-plugin#154]
# Bug report

## Description

While using lodash-webpack-plugin (v.0.11.5) react-google-maps (v9.4.5) doesn't work properly without emitting any errors to console in dev and prod builds. react-google-maps shows blank grey space.

## Steps to reproduce

Clone below repro repo, install dependencies (npm i) and run it locally (http://localhost:8000).
- Repro repo:
> https://github.com/aziolek/bug-repro-repo-lodash-webpack-plugin
- To run it locally without lodash-webpack-plugin:
> npm run nlwp
- To run it locally with lodash-webpack-plugin:
> npm run wlwp

See the difference. Ignore google maps dev mode and load warning, they don't matter.

## Expected behavior

react-google-maps works while using lodash-webpack-plugin.

### OS
- Linux Mint 18.3 Cinnamon 64-bit

### Browser

- Google Chrome - Version 67.0.3396.87 (Official Build) (64-bit)
- Firefox Quantum - Version 60.0.2 (64-bit)

![working](https://user-images.githubusercontent.com/25887234/41773682-3a4bae12-761d-11e8-8bfc-483edc3f914f.jpg)
![notworking](https://user-images.githubusercontent.com/25887234/41773683-3a667cce-761d-11e8-869c-11ee2ab28824.jpg)

**Comment by falsyvalues** [comment]
Hi @aziolek!

Did you try to enable one of the [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets) in lodash-webpack-plugin? There was similar issue #119.

**Comment by aziolek** [comment]
Hi @falsyvalues.
Thank you for your response.

I've just tried using `"currying": true, "flattening": true` and only `"curring": true`, as suggested in [#119](https://github.com/lodash/lodash-webpack-plugin/issues/119). Still doesn't work.

**Comment by falsyvalues** [comment]
@aziolek Please try to enable them all. I saw `_.get` usage in **react-google-maps** source which require `paths` option, so check them all and verify.

**Comment by aziolek** [comment]
@falsyvalues : using `collections: true` fixes the issue. Thank you for your help.

**Comment by falsyvalues** [comment]
Rock 😃!

**Comment by dyf19118** [comment]
It will affect all third party libraries that take lodash as dependency, not just react-google-maps.
It's not possible and not reasonable to know which part of lodash third parties have taken in use.

**Comment by jdalton** [comment]
@dyf19118 lodash-webpack-plugin is for application bundles. Those applications tend not to re-expose their consumed lodash for third-party use.

**Comment by davidhouweling** [comment]
@jdalton I have the same thoughts as @dyf19118. I'm not sure what you mean by "re-expose their consumed lodash", wouldn't it be that applications should use the same lodash throughout (as in directly or via dependencies)?
