### ISSUE TITLE
What feature does _.toArray belong to?

### ISSUE THREAD

**Issue by CoderK** [lodash/lodash-webpack-plugin#155]
Lodash has defined _.toArray as Lang.

![image](https://user-images.githubusercontent.com/1631348/42200490-7977ea42-7ece-11e8-91d3-b5330c72cfb3.png)

What feature of lodash-webpack-plugin does it belong to?

**Comment by jdalton** [comment]
Hi @CoderK!

You can modify it with `exotics` and `unicode` options.

**Comment by CoderK** [comment]
@jdalton 

Thanks for your quick answer!!
