### ISSUE TITLE
when i use get, it should depends on  _baseGet , but load getValue

### ISSUE THREAD

**Issue by bless4ever** [lodash/lodash-webpack-plugin#157]
_.get which depends on internal baseGet, got fed a flat getValue instead, and it broke the whole app.
![image](https://user-images.githubusercontent.com/9196077/49268297-b2b24000-f499-11e8-8f0f-92a880ff3a56.png)

**Comment by jdalton** [comment]
Hi @bless4ever!

The `lodash-webpack-plugin` works by removing extra functionality so you start from bare bones and opt-in to other functionality. Please see the list of togglable features and enable the relevant ones.
