### ISSUE TITLE
Tell the user of overrides or throw an error

### ISSUE THREAD

**Issue by francois2metz** [lodash/lodash-webpack-plugin#158]
Hi,

We had a weird issue that happened randomly when compiling our assets. We were using `cloneDeep` without enabling the `cloning` option. Most of the time the bundle had the correct behavior (full `cloneDeep`), sometimes not (only `identify`). 
I think it would be better to tell the user of the overrides, by outputting a warning message or throwing an error. 

What do you think?

**Comment by ishaba** [comment]
Hey,

I have quite similar issue with my bundle randomly includes some lodash functions and sometimes not, you can make two builds in a row and one will have some code and another not, my investigation directed me to this plugin but i steel don't know how to fix it

**Comment by francois2metz** [comment]
If you enable the corresponding option this fixed my build. The problem is I didn't knew that I had to enable it because it worked for month correctly. At least a warning could help.

**Comment by jdalton** [comment]
Hi @francois2metz!

If you'd like to open a PR to work through that I'd be up for it. Thanks!

**Comment by aniude** [comment]
```javascript
new LodashModuleReplacementPlugin({
      cloning: true,
      exotics: true     
});

```

It workaround.
