### ISSUE TITLE
Does a rollup alternative make sense?

### ISSUE THREAD

**Issue by AndyOGo** [lodash/lodash-webpack-plugin#159]
We provide package ESM builds internally and bundle them up by rollup.
This webpack plugin is great, and every team can just add it to it's build.

Though I'm thinking if it would make sense to have such a plugin also for rollup 🤔

**Comment by jdalton** [comment]
Hi @AndyOGo!

This plugin used to also low-key work as a rollup plugin out of the box. I've heard reports that this is no longer the case. If you're interested in patching that back up I'm open to a PR.

**Comment by AndyOGo** [comment]
Hi @jdalton 
Thanks for your quick answer.
Alright. Personally I really like the idea.
