### ISSUE TITLE
Is it supposed to detect import from libraries?

### ISSUE THREAD

**Issue by ruiaraujo** [lodash/lodash-webpack-plugin#16]
I just fixed an issue while using redux-form v6 where partialRight seemed to be behaving like partial until I reenabled curry support.

While the "fix" makes sense, I thought the plugin would process the require call and enable it automatically.
This is the compiled required of partialRight which seemed to be causing the issue.
`var _partialRight2 = require('lodash/partialRight');`

**Comment by jdalton** [comment]
It detects usage for stubs, those replaced with `identity` and `noop` at the moment.
I think I can tackle this case though.

**Comment by ruiaraujo** [comment]
Thanks for the quick fix. ;)
