### ISSUE TITLE
pack the wrong function

### ISSUE THREAD

**Issue by EnjoyChan** [lodash/lodash-webpack-plugin#168]
I think it's a serious problem.  it  does make a mistake
![image](https://user-images.githubusercontent.com/6998403/77133246-61b6c880-6a9d-11ea-80a3-1a7bb49e871f.png)

**Comment by bnjmnt4n** [comment]
This is not an issue: lodash-webpack-plugin replaces modules with simpler versions of functions based on the feature sets you enable.
