### ISSUE TITLE
import get method on demand error

### ISSUE THREAD

**Issue by yuzihan30** [lodash/lodash-webpack-plugin#170]
import _ from lodash

console.log('testget', _.get({ a: { b: 1 } }, 'a.b', ''))  // '' error
console.log('testclonedeep', _.cloneDeep({ a: { b: 1 } })) // {a:{b:1}} right

**Comment by humorHan** [comment]
I had the same problem.
Import on demand causes method exception
@jdalton

**Comment by falsyvalues** [comment]
You have to set proper [feature flags](https://github.com/lodash/lodash-webpack-plugin#feature-sets) or don't use this plugin at all (if everything is needed).
