### ISSUE TITLE
Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead.

### ISSUE THREAD

**Issue by creage** [lodash/lodash-webpack-plugin#174]
This plugin is not compatible with latest Webpack anymore (v5), as it has some API changes. 

Please see details here https://github.com/webpack/webpack/issues/11647

**Comment by spnc-omz** [comment]
same as: https://github.com/lodash/lodash-webpack-plugin/issues/167 ?

**Comment by TomFoyster** [comment]
This line needs to be removed for v5 support;

https://github.com/lodash/lodash-webpack-plugin/blob/master/src/index.js#L45

I replaced it with the below to try and support <5.1.0 too;
```
/* Support for Webpack >= 5.1.0 */
if(!compiler.webpack) {
    return data
}
```

(`compiler.webpack` was only added in `5.1.0`) 

This works in my App but I can't check tests pass as they fail with version 5 it seems.

**Comment by bnjmnt4n** [comment]
Marking this as a duplicate of #167.
