### ISSUE TITLE
Rename to lodash-webpack-plugin

### ISSUE THREAD

**Issue by ericclemmons** [lodash/lodash-webpack-plugin#2]
I know I asked this of myself when creating plugins, and the convention seems to be a suffix, not prefix:
> https://www.npmjs.com/search?q=webpack-plugin

Also followed by the author:
> https://github.com/webpack?utf8=%E2%9C%93&query=plugin

Granted, my typo'd, mobile tweet didn't come across too convincingly :)
> https://twitter.com/ericclemmons/status/725886813491986432

**Comment by ericclemmons** [comment]
It's also available:
> https://www.npmjs.com/package/lodash-webpack-plugin

**Comment by jdalton** [comment]
Thanks!
