### ISSUE TITLE
Flow usage should include baseFlatten

### ISSUE THREAD

**Issue by ruiaraujo** [lodash/lodash-webpack-plugin#22]
I am using flow to compose functions. 0.8.0 broke the flow function because of baseFlatten.

Since it doesn't seem obvious to me that flow must include `flattening`, it should enable it internally.

**Comment by jdalton** [comment]
I thought about this and almost had exceptions put in but the `_.flow` method is documented to accept an array of functions. You can use it without argument flattening by passing an array.

**Comment by ruiaraujo** [comment]
ok. got it.

**Comment by ruiaraujo** [comment]
maybe add a mention to the README? ;-)

**Comment by jdalton** [comment]
I'm open to a PR. If you'd like to do it.

**Comment by jdalton** [comment]
Maybe something about rest arguments.

**Comment by ruiaraujo** [comment]
I will put up on Monday a PR with a caveat section for the README to help new users.
