### ISSUE TITLE
can i use this lib as a gulp plugin?

### ISSUE THREAD

**Issue by taoqf** [lodash/lodash-webpack-plugin#29]
i cannot use babel-loader because some reasons [https://github.com/babel/babel-loader/issues/259](https://github.com/babel/babel-loader/issues/259)

i tried to use this lib just as a webpack plugin, but i could not see any changes.
is there a way i use this lib just as a gulp plugin?
i find the plugin, like uglify for webpack is not as well as it works as gulp plugin.

**Comment by jdalton** [comment]
I can't act on "some reasons".
