### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jbalboni** [lodash/lodash-webpack-plugin#30]
It looks like this plugin does not work on Windows because of slash direction in the file paths. [This regex check](https://github.com/lodash/lodash-webpack-plugin/blob/master/src/index.js#L32) always returns because the paths it's sent look like `...node_modules\lodash\_getLength.js`. If I modify the code to replace backslashes in `resource` with forward slashes, the plugin works as expected.

**Comment by jdalton** [comment]
Rock, thanks for filing!
