### ISSUE TITLE
Incorrect result for `includes(string, substring)`

### ISSUE THREAD

**Issue by dotch** [lodash/lodash-webpack-plugin#31]
When using this plugin:
`includes('abcdefghijklmnop', 'fgh')` returns `false`
without the plugin, I get the correct result: `true`.

I created a minimal example here: https://github.com/dotch/lodash-webpack-plugin-bug

**Comment by jdalton** [comment]
Hi @dotch!

You'll have to enable "collections" support. See https://github.com/lodash/lodash-webpack-plugin#usage

**Comment by dotch** [comment]
Ah, thanks for the quick response!
