### ISSUE TITLE
Is this plugin still recommended when using webpack v2 along with its tree shaking ability?

### ISSUE THREAD

**Issue by ctrlplusb** [lodash/lodash-webpack-plugin#34]
Not much to add on top of the question above. :)

**Comment by jdalton** [comment]
Hi @ctrlplusb!

I think this question is better directed towards [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash), but yes it's still recommended. Webpack v2 and rollup both fail to tree shake Lodash properly. This plugin takes things up a notch by remapping paths, cutting extra features, to reduce build size

**Comment by ctrlplusb** [comment]
Brilliant, thanks!

**Comment by fisch0920** [comment]
👍
