### ISSUE TITLE
Victory.js victory-chart & lodash-webpack-plugin Incompatibility

### ISSUE THREAD

**Issue by joshburgess** [lodash/lodash-webpack-plugin#38]
I'm not sure where this should go, so I'm just going to post it in both repos & link them, but I'm having an issue where using lodash-webpack-plugin for my production build is breaking some internal code in the victory.js victory-chart library. 

Specifically, it's in the scale.js helper utility and is failing on line 71:

var axisData = allData.map(accessor);

The error in the chrome console is:

scale.js:71 Uncaught TypeError: r.map is not a function

And this was while using a horizontal stack chart made up of VictoryStack & VictoryBar components.

To be clear, if I comment out usage of the lodash webpack plugin and rebuild, all works as it should. I'm not sure what exactly the issue is, but let me know if I can provide any extra detail you might need. 

FormidableLabs/victory-chart#289

**Comment by jdalton** [comment]
Looks like they're taking care of ya on FormidableLabs/victory-chart#289.
