### ISSUE TITLE
I was surprised by the removal of sugar

### ISSUE THREAD

**Issue by wmertens** [lodash/lodash-webpack-plugin#40]
While this plugin has a very noticeable impact on package size, it was a surprise that it broke my build.

I would expect default settings to not break builds :)

So I suppose this is at least a request for better documenting what the feature removal does, and what features need to be enabled to make things work.

For example, it took me a while before figuring out that I needed to add `shorthands: true` to make string-as-an-iteratee work. I don't really understand what the other features do, a somewhat longer explanation would be appreciated.

**Comment by jdalton** [comment]
Yep, string as an iteratee is an iteratee shorthand. This behavior is by design.

**Comment by wmertens** [comment]
I realize that now, I just meant that that was not obvious from the readme. Some guidance for would-be installers would be appreciated.
