### ISSUE TITLE
_.reduce and objects

### ISSUE THREAD

**Issue by ekmartin** [lodash/lodash-webpack-plugin#46]
Hi!
Seems like _.reduce is mapped to `arrayReduce`, which removes its ability to reduce objects as well? 

Using babel-plugin-lodash my reduce call is turned into:
![screen shot 2016-07-21 at 11 15 39](https://cloud.githubusercontent.com/assets/3536982/17017820/34ba2624-4f35-11e6-957c-a1e23e5f3afe.png)

And when I add lodash-webpack-plugin into the mix it's turned into:
![screen shot 2016-07-21 at 11 20 26](https://cloud.githubusercontent.com/assets/3536982/17017831/3f0fff04-4f35-11e6-85a5-5c88bf75452e.png)

Is this a bug or am I doing something wrong?

**Comment by jdalton** [comment]
You need to enable the ["collections" feature](https://github.com/lodash/lodash-webpack-plugin#feature-sets).

**Comment by ekmartin** [comment]
Ah, I should've seen that - thank you! Sorry for wasting your time.

**Comment by jdalton** [comment]
No worries.
