### ISSUE TITLE
`find` shorthand doesn't seem to work

### ISSUE THREAD

**Issue by ericgio** [lodash/lodash-webpack-plugin#48]
Hey there, great plugin, thanks! When I do the following in my code

```
_.find(users, {'active': true});
```
I get `Uncaught TypeError: predicate is not a function`

Everything works when I convert to a function, eg:
```
_.find(users, o => o.active);
```

Is this expected, and if so, are you planning on adding support for shorthand?

Thanks!

**Comment by jdalton** [comment]
You have to enable the `"shorthands"` [feature set](https://github.com/lodash/lodash-webpack-plugin#feature-sets).

**Comment by ericgio** [comment]
Ah, got it. Thank you.
