### ISSUE TITLE
Weird behavior with _.get and _.has

### ISSUE THREAD

**Issue by bebraw** [lodash/lodash-webpack-plugin#52]
After upgrading my project to use lodash-webpack-plugin, I started getting test failures related to `_.get` and `_.has`.

I set up [a branch](https://github.com/reactabular/reactabular/tree/lodash-webpack) if you want to have a look. You can find run instructions below `CONTRIBUTING.md`.

**Comment by jdalton** [comment]
You probably need to enable deep property paths. See the [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets) section.

```js
new LodashModuleReplacementPlugin({ paths: true })
```

**Comment by bebraw** [comment]
Makes sense! Thanks.

**Comment by jdalton** [comment]
Since you're using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) too you can change:
```js
import get from 'lodash/get';
import has from 'lodash/has';
```
into
```js
import { get, set } from 'lodash';
```
