### ISSUE TITLE
Problems with FP flow

### ISSUE THREAD

**Issue by luisherranz** [lodash/lodash-webpack-plugin#53]
I'm having problems with lodash fp.

This works as expected if I don't use `lodash-webpack-plugin`:
```javascript
import { flow, keyBy, mapValues } from 'lodash/fp';

const mappedPackages = flow(
  keyBy(pkg => pkg.namespace),
  mapValues(pkg => pkg.name)
)(packages);
```

But if I use it, it doesn't work, it just returns the original array.

This is the config I am using:
```javascript
new LodashModuleReplacementPlugin({ currying: true }),
```

If I don't use `currying: true` I get an error, which is expected. Using `currying` I just get the same array I input to the flow function.

**Comment by jdalton** [comment]
Flow usage without `'flattening'` uses an array of functions like `flow([func1, func2])`.

**Comment by luisherranz** [comment]
Ok, thanks. I wasn't able to find that in the docs.

**Comment by luisherranz** [comment]
I've tried both with array `flow([func1, func2])` and with `flattening` but they didn't work.

Finally, I removed the babel lodash plugin from .babelrc and it worked, so the problem seems to be `babel-plugin-lodash`.

I've looked at the docs and I didn't see anything related to fp. Should it work? Do I need to configure anything else? Do you want me to open an issue there?

**Comment by jdalton** [comment]
Without `babel-plugin-lodash` I doubt `lodash-webpack-plugin` is having much of an impact.

**Comment by luisherranz** [comment]
Any suggestion about why this is not working? The same code without babel&webpack plugins works just fine.

**Comment by luisherranz** [comment]
I can try to make a simpler repo reproducing the problem.

**Comment by luisherranz** [comment]
There you go:
https://github.com/luisherranz/webpack-lodash-plugin-problem

I hope it helps.

**Comment by jdalton** [comment]
Thanks!

Looks like you'll need to add `placeholders: true`.

**Comment by luisherranz** [comment]
Yeah, it's finally working with:
```javascript
new LodashPlugin({ currying: true, flattening: true, placeholders: true })
```

Thanks! I'm not lodash expert (though I love it) so the naming used in your Feature Sets is hard to understand for me.
