### ISSUE TITLE
Bundle Size Expectations

### ISSUE THREAD

**Issue by fisch0920** [lodash/lodash-webpack-plugin#61]
I just want to make sure I'm getting the optimal benefit from this great plugin.

Pre-plugin, bundled size for lodash was ~1.04mb.  After applying plugin with default options, I'm at 612.54 KB which still seems pretty large.

Is this reasonable and what's expected?  If so, would you mind adding a note to the README with some basic details about the size savings?

Thanks!!

**Comment by jdalton** [comment]
You should look to minifying your code with the webpack optimization plugins:
```js
  'plugins': [
    new LodashModuleReplacementPlugin,
    new webpack.optimize.OccurrenceOrderPlugin,
    new webpack.optimize.UglifyJsPlugin
  ]
```
This will minify your bundle. Then when looking at the size I recommend using [gzip-size-cli](https://www.npmjs.com/package/gzip-size-cli) and [pretty-bytes-cli](https://www.npmjs.com/package/pretty-bytes-cli):
```shell
webpack index.js bundle.js && gzip-size bundle.js | pretty-bytes
```
