### ISSUE TITLE
_.uniq doesn't work with array >= 200 items unless caching: true

### ISSUE THREAD

**Issue by elado** [lodash/lodash-webpack-plugin#64]
Could be a a `lodash` bug, when sets aren't included and an array with `LARGE_ARRAY_SIZE` is given.

```js
_.uniq(new Array(200).fill(1))

TypeError: seen.push is not a function
    at baseUniq (_baseUniq.js:64)
    at uniq (uniq.js:23)
    at Array.uniq (uniq.js:6)
```

**Comment by jdalton** [comment]
@elado Thanks for the heads up!

**Comment by jdalton** [comment]
This is due to the use of `new SetCache` in `baseUniq`. When `SetCache` is replaced with `identity` and then called as a constructor with no arguments it will return an empty object instead of an array value.
