### ISSUE TITLE
_.property seems not work when shorthands enabled

### ISSUE THREAD

**Issue by hustcer** [lodash/lodash-webpack-plugin#65]
`_.property` seems not work when `shorthands` was enabled, however, it works when `paths` was enabled, that's what I have found, which is different from `README.md`

Env:
lodash@4.16.4
lodash-webpack-plugin@0.10.2
webpack@2.1.0-beta.25
node@v6.7.0

**Comment by jdalton** [comment]
Hi @hustcer!

I believe `_.property` should still work when `shorthands` are enabled it just lacks deep property path support unless `paths` is enabled.

**Comment by hustcer** [comment]
Then according to what you have said we have to set at least `{shorthands:true, paths:true}` to make `_.property` work, however, `{shorthands:false, paths:true}` works.
I don't think it's an `invalid` issue, although you can labelled it as `won't fix`, as it's not a `big` issue.

**Comment by jdalton** [comment]
The `_.property` method should work with or without `shorthands`. It just won't support deep property paths, unless you enable `paths`. It still works with non-deep paths (the common usage).

**Comment by hustcer** [comment]
I see, thanks
