### ISSUE TITLE
Support for lodash v3

### ISSUE THREAD

**Issue by tquetano-r7** [lodash/lodash-webpack-plugin#68]
I was just curious if there was a version of this plugin that supports lodash v3. Unfortunately due to other dependencies my project is forced to remain on v3.10.1 of lodash for the time being, but I was hoping if possible to make use of this plugin. It's a shot in the dark, totally understand if you only support the much more well-structured v4 of lodash.

**Comment by jdalton** [comment]
Hi @tquetano-r7!

Our module remapping is really for `lodash@^4.0.0`. So while some will work others, like the high impact "shorthands" feature set remap may not.
