### ISSUE TITLE
Should probably merge lodash + lodash-es... or deprecate the later one

### ISSUE THREAD

**Issue by swernerx** [lodash/lodash-webpack-plugin#72]
While this plugin and the babel plugin are very nice, I am not sure about what the "normal" user of different libraries is expected to do. Right now we see dependency variations in our build where a lot of them are related to lodash.

Three different kinds seem to produce a lot of duplication/redundancy right now:

- Lodash Classic Build: https://www.npmjs.com/package/lodash
- Lodash ES Build: https://www.npmjs.com/package/lodash-es
- Lodash Single Packages: e.g. [lodash.merge](https://www.npmjs.com/package/lodash.merge)

Problem is a typical project consists of own dependencies and third party dependencies. A very prominent example right now might be redux which itself uses both `lodash` and `lodash-es`. Our code uses the normal `lodash`. And some third party dependencies also use variations of the same code. 

Compared to other libraries lodash is published in all these variants and a normal webpack is unable to identify common parts.

Is there anything like this being worked on as part of the plugin? Otherwise lodash itself should probably deprecate the es-build and single packages and instead should suggest using the normal build + the webpack/babel plugins.

**Comment by jdalton** [comment]
Hi @swernerx!

Nothing planned plugin wise but see the [v5 roadmap](https://github.com/lodash/lodash/wiki/Roadmap).

**Comment by swernerx** [comment]
Interesting! If a modular es2015 is the new default, it should maybe mention that "lodash-es" is discontinued as well.

Maybe it would make sense to community this roadmap more clear when even big players like redux are using a mix-match of different lodash concepts.

**Comment by jdalton** [comment]
> Interesting! If a modular es2015 is the new default, it should maybe mention that "lodash-es" is discontinued as well.

lodash-es will become the new master branch we'll still have the transpiled npm package variant.
