### ISSUE TITLE
predicate is not a function

### ISSUE THREAD

**Issue by MinionsHero** [lodash/lodash-webpack-plugin#79]
Hello,

It makes an error  when I use  `import findIndex from 'lodash/findIndex'`  with lodash-webpack-plugin，the console shows that “Uncaught TypeError: predicate is not a function(…)“，the error  can be located to baseFindIndex。

Thanks very much！

**Comment by jdalton** [comment]
By default the "shorthands" [feature set](https://github.com/lodash/lodash-webpack-plugin#feature-sets) is disabled. I recommend avoiding it because it's pretty heavy. Instead use the `_.property`, or `_.matches` helper directly.

**Comment by EmaileriMikko** [comment]
@jdalton Could you give an example how the index is found with `_.property` or `_.matches`?

For example
```
const array = [
	{ id: 100, ... },
	{ id: 101, ... },
	{ id: 102, ... },
	{ id: 103, ... },
];

_.findIndex(array, { id: 102 }) // 2
```

**Comment by jdalton** [comment]
@EmaileriMikko See the [_.matches](https://lodash.com/docs/4.17.4#matches) docs.

**Comment by kmvan** [comment]
`import { findIndex } from 'lodash'
`
Is it right?

**Comment by MinionsHero** [comment]
To add shorthands:true in lodash-webpack-plugin options will work!

**Comment by taewo** [comment]
` plugins: [
      new LodashModuleReplacementPlugin({
        'shorthands': true
      })
    ]` works perfect in my case.
