### ISSUE TITLE
_.union not working unless `flattening` is enabled

### ISSUE THREAD

**Issue by max-mathieu** [lodash/lodash-webpack-plugin#81]
`_.union([1,2], [2,3])` returns `[1,2]` (actually always the first argument) unless `flattening` is enabled. The solution is to write `_.uniq(_.concat([1,2],[2,3]))` or opt in to `flattening` options.

I wonder what's the best solution here, as the link between `flattening` and `union` is not immediate and the _.union is just not doing its work by default. Maybe include that in the table of opt-ins that _.union needs `flattening`?

**Comment by jdalton** [comment]
Thanks for the heads up @max-mathieu!

**Comment by max-mathieu** [comment]
Oh nice, I did not see that fancy overrides things. I could have submitted a PR :)

Thanks for the quick fix!
