### ISSUE TITLE
forEach being replaced by arrayEach

### ISSUE THREAD

**Issue by bruno12mota** [lodash/lodash-webpack-plugin#82]
I'm using lodash/forEach in a project and it works perfectly. When I tried to use this plugin the code was behaving incorrectly with no errors being output.

After some debugging I reached to the issue, basically (dunno why) instead of getting the forEach function the plugin was replacing it by the arrayEach. Since I was passing an object to the supposed forEach function, it wasn't looping. Any idea why?

**Comment by bruno12mota** [comment]
Maybe I'm not getting the goal of this project

**Comment by bruno12mota** [comment]
Just seen it's on the mapping file https://github.com/lodash/lodash-webpack-plugin/blob/master/src/mapping.js

**Comment by jdalton** [comment]
Hi @bruno12mota!

This is by design. By default several [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets) are disabled to reduce bundle sizes. One of the feature sets disabled by default is `collections`. You can enable them though like:

```js
new LodashModuleReplacementPlugin({
  'collections': true
});
```

**Comment by bruno12mota** [comment]
Sorry about that, I completely missed that 😅
