### ISSUE TITLE
Errors in build after usage

### ISSUE THREAD

**Issue by swernerx** [lodash/lodash-webpack-plugin#86]
This is mainly a complain that is was not obvious - by readings the docs - that this plugin is actually totally risky. I mean everybody wants to have smaller builds - that's an easy sell - but this plugin is breaking in hundreds of places in our applications because I figured out - probably too late - that this is changing the behavior of "get" to not handling deep objects anymore - making it pretty useless overall.

I think it should made much more clear - probably also on the safer "babel-plugin-lodash" - that this is not just a plugin for making smaller builds but that the price is that it changes behavior of code from the original source code and that this might break code in production. 

Because of the "compression" nature of this plugin we only used it for our production builds - like Uglify - and this was probably the worst decision yet. I figure I trusted the name "lodash" for super stability, rich test suites, etc.

**Comment by jdalton** [comment]
The first line of the readme spells things out pretty clearly:
>Create smaller Lodash builds by replacing feature sets of modules with noop, identity, or simpler alternatives.
