### ISSUE TITLE
Issues with the minified code

### ISSUE THREAD

**Issue by okonet** [lodash/lodash-webpack-plugin#9]
I've got this issue with the minified code:

```
Uncaught TypeError: t is not a function
```

and after bisecting the recently changed code it looks like the commit that introduces it is the added `lodash-webpack-plugin` and bumping `lodash` from `4.11.2` to `4.12.0`.

Here is the exceprt from the console:

![2016-05-10 at 15 54](https://cloud.githubusercontent.com/assets/11071/15148970/1420c468-16c8-11e6-849c-12313e4cb02c.png)

Any idea what this can be?

**Comment by jdalton** [comment]
Remove the UglifyJSPlugin and see the unminified result.

**Comment by jdalton** [comment]
It doesn't look like it belongs to Lodash though.

The `lodash-webpack-plugin` removes features. You can try enabling them all and removing them one by one to see which one hits the problem with your code.

**Comment by okonet** [comment]
@jdalton thanks for jumping in so quckly. I've disabled the UglifyJS and here is the failing code:

![2016-05-10 at 16 18](https://cloud.githubusercontent.com/assets/11071/15149718/ebf5dfca-16ca-11e6-87a0-5cb3e242cb96.png)

**Comment by jdalton** [comment]
Ah the `e.e` was `module.e`. That looks ok but ok.

With `lodash-webpack-plugin` by default iteratee `shorthands` are disabled so you have to provide functions.

**Comment by okonet** [comment]
I still don't quite get it, to be honest. I'm not using arrayMap and not sure what method is, so it will be a though to debug. Would adding `shorthands: false` fix it?

**Comment by jdalton** [comment]
Add `collections` and `shorthands`.

**Comment by jdalton** [comment]
```js
new LodashModuleReplacementPlugin({
  'collections': true,
  'shorthands': true
});
```

**Comment by Dimon70007** [comment]
Hi guys. Thanks for your hard work. I had the same problem. Options that was listed above did not help, but I have resolved it with only `'shorthands': true` option. 
Be happy
