### ISSUE TITLE
startCase("howdy-there") requires `unicode: true`

### ISSUE THREAD

**Issue by ericclemmons** [lodash/lodash-webpack-plugin#92]
Hi! 👋 

You may remember from <https://twitter.com/ericclemmons/status/821827334319771648?s=09> that I ran into issues before with this plugin.

It's working fairly well now, but I found the original problem:

### `lodash`

```js
startCase("howdy-there")
// Howdy There
```

### `lodash` + `webpack-lodash-plugin`

```js
startCase("howdy-there")
// HowdyThere
```

Adding `unicode: true` resolves it.

Is this the expected behavior?

- - -

_Unrelated, I thought I'd share the positive impact this plugin currently has from our internal project:_ 
> With lodash-webpack-plugin, the lodash example went from 53.1 kB to 7.23 kB.
> For widgets.js this takes us from 171 kB to 124 kB (46.8 kB to 36.5kB gzipped).

**Comment by jdalton** [comment]
Hi @ericclemmons!

I can't repro the issue with `lodash@4.17.4`, `lodash-webpack-plugin@0.11.0`, and `webpack@2.2.0`. You might try upgrading.

**Comment by ericclemmons** [comment]
First, **sorry that I pasted the wrong example**!

I just updated dependencies and narrowed it to _this_ scenario:

### `lodash`'s website (Correct)

```js
console.log(startCase("howdyThere")); // Howdy There
console.log(startCase("HowdyThere")); // Howdy There
console.log(startCase("howdy-there")); // Howdy There 
```

### My `lodash` + `lodash-webpack-plugin` project (Incorrect)

```js
console.log(startCase("howdyThere")); // howdyThere
console.log(startCase("HowdyThere")); // HowdyThere
console.log(startCase("howdy-there")); // Howdy There 
```

**Comment by jdalton** [comment]
🐛 !

**Comment by ericclemmons** [comment]
If you could point me in the right direction, I can make a test for it.  I wasn't 100% sure where it'd go in the test base...

**Comment by jdalton** [comment]
No worries. The fix could go one of two ways. 1) I modify what is removed by `unicode` or 2) I force case methods to auto-enable `unicode`. Since v4 releases have ended I can't fix the code paths.

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash-webpack-plugin/commit/dac2fcd17f9251e0e593969ccd56445b634744a5 and https://github.com/lodash/lodash-webpack-plugin/commit/d9fddfeb0baab0c1869760a7aaa6a518e72d9e47.
