### ISSUE TITLE
Aliasing lodash as lodash-es breaks _.padStart with this plugin

### ISSUE THREAD

**Issue by marksamman** [lodash/lodash-webpack-plugin#96]
Webpack config:
```js
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

module.exports = {
	resolve: {
		alias: {
			'lodash': 'lodash-es'
		}
	},
	entry: [ './index' ],
	output: {
		filename: '[name].js'
	},
	plugins: [
		new LodashModuleReplacementPlugin,
	]
};
````

index.js
```js
import _ from 'lodash';
document.write(_.padStart(1, 2, '0'));
```

Versions:
* lodash-es: 4.17.4
* lodash-webpack-plugin: 0.11.0
* webpack: 2.2.1

Actual output:
1

Expected output:
01

**Comment by jdalton** [comment]
Hi @marksamman!

It has nothing to do with specifying `lodash` as an alias of `lodash-es`. You're providing invalid input as pad is a "String" method. If you want to continue to do that you'll need to enable the "coercions" feature set in the lodash-webpack-plugin options.

**Comment by marksamman** [comment]
Thanks! It works fine without the alias though, but perhaps the plugin isn't being used then.

**Comment by arasabbasi** [comment]
Missing paranthesis in 

`new LodashModuleReplacementPlugin,`
