### ISSUE TITLE
`.sortBy` fails with this plugin

### ISSUE THREAD

**Issue by xingrz** [lodash/lodash-webpack-plugin#99]
```json
"lodash": "^4.17.4",
"babel-plugin-lodash": "^3.2.11",
"lodash-webpack-plugin": "^0.11.2",
```

According to lodash's documentation, the second parameter of `.sortBy` should be either a function or a array of function.

> Arguments
>
> * collection (Array|Object): The collection to iterate over.
> * [iteratees=[_.identity]] (...(**Function|Function[]**)): The iteratees to sort by.

But after applying this plugin, the below fails:

```js
import { sortBy } from 'lodash';
sortBy([ 3, 2, 5, 1 ], i => i);
```

while the below still works:

```js
import { sortBy } from 'lodash';
sortBy([ 3, 2, 5, 1 ], [ i => i ]);
```

**Comment by jdalton** [comment]
Hi @xingrz!

This is by design. If you'd like to support passing single value you'll need to enable the `flattening` feature set.

**Comment by xingrz** [comment]
Oh, thank you!

**Comment by timdorr** [comment]
Ran into this myself just now. But I'm confused about this:

> If you'd like to support passing single value you'll need to enable the flattening feature set.

OK, well neither of these appear to work:

```js
new LodashModuleReplacementPlugin({
  flattening: true
})
// or
new LodashModuleReplacementPlugin({
  flattening: false
})
```
I'm confused as to how you're supposed to do this. Can you help this dense guy out?
